listener 1883 0.0.0.0
protocol mqtt

allow_anonymous false
password_file /run/secrets/mosquitto_password_file
acl_file /mosquitto/config/acl

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

max_connections 100
max_inflight_messages 20
max_queued_messages 100
max_packet_size 16384
